### ISSUE TITLE
Asking for 

### ISSUE THREAD

**Issue by kaniska** [ecesena/oscars2016#1]
Can you please provide the implementation of the custom class - KafkaIOWriteBoundStreamingTranslator (or similar one) that you have registered in FlinkStreamingTransformTranslators.

> > TRANSLATORS.put(KafkaIO.Write.Bound.class, new KafkaIOWriteBoundStreamingTranslator());

I am bit stuck up while sending data using DataStream<String> dataSink,
so much appreciate your help.

**Comment by 0x0ece** [comment]
Hey, sorry for the delay. I saw the thread also on Beam's user ml. Are you ok with that?
My version was on really old code, based on flink 0.10 and hacking flink-dataflow. Definitely a lot of things have changed, I'd really recommend to look at the Beam solution.

**Comment by kaniska** [comment]
Thanks, I posted the question to beam forum and got a solution thats
working for me.

**Comment by 0x0ece** [comment]
Awesome, that's what I was referring to. Closing this one then.
